### ISSUE TITLE
Convert GEAR_ID to utilize Archer's "Tracking ID" and change all relationships

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/GEAR3#2]
Tracking ID is Archer's UID field for FISMA sub/systems. Previously, the Archer team had a GEAR_ID field which, in cases where there were existing GEAR FISMA systems, was used as the unique ID (UID). To reduce complexity going forward, we want to align GEAR with Archer's "Tracking ID" field so that Archer isn't keeping track of legacy GEAR UIDs and both systems are using the same ID. 

Use [David Ellis's list](https://docs.google.com/spreadsheets/d/1_RFnQ0OsB-AP73CRuLLdlpEqbSbIPsEFEP0WgbTAwn4/edit#gid=378847851&fvid=991343420) of GEAR IDs that he's changed due to a FISMA system having a legacy GEAR UID. (Filter on GEAR ID column not being equal to "" and use the "Tracking ID" field for all FISMA systems).
In GEAR's database, change the FISMA system lookup tables for:
- [ ] technology mapping (using the business application to technology mapping)
- [ ] capabilities mapping (again, using bus app mapping)
- [ ] TIME mapping
- [ ]  Interfaces
- [ ] Others as identified (possibly POC?)
